import Layout from '../components/layout/Layout';
import { Button, SectionIntro, Tag } from '../components/manifest-site';

const principles = [
  { title: 'Earn trust through clarity', copy: 'We explain constraints, options, and risks in plain language. Ownership, data handling, and responsibilities are part of the plan—not details left for later.' },
  { title: 'Choose appropriate technology', copy: 'The best stack is the one that fits the users, operating team, and lifecycle. We avoid adding tools or complexity without a clear reason.' },
  { title: 'Stay accountable after launch', copy: 'Digital platforms keep changing. We can remain involved through maintenance, technical planning, and product improvements as priorities evolve.' },
];

export default function AboutPage() {
  return <Layout><div className="mfts-site">
    <header className="mf-page-hero"><div className="mf-container"><p className="mf-eyebrow">ABOUT MANIFEST FTS / FORWARD THINKING SOLUTIONS</p><h1>An engineering-led partner for important digital work.</h1><p>Manifest FTS works with organizations to design, build, and support technology that is understandable, useful, and durable.</p><div className="mf-hero__actions"><Button href="/contact">Talk with our team ↗</Button><Button href="/work" variant="secondary">View client stories</Button></div></div></header>
    <section className="mf-section"><div className="mf-container mf-grid-2" style={{alignItems:'start'}}><div><p className="mf-eyebrow">WHO WE ARE</p><h2 className="mf-title">We connect strategy with the work of building.</h2></div><div className="mf-body-copy"><p>Manifest FTS is a digital engineering partner. Our work spans product design, UX, full-stack development, content platforms, managed infrastructure, and ongoing technical support.</p><p>We collaborate with client teams to understand how their organizations operate and what their digital systems need to do. Then we select a sensible path, implement it carefully, and stay available as the platform grows.</p><p>We believe data trust and security are part of good engineering. That means clear account ownership, considered access, backup planning, and honest communication about provider boundaries and operational risk.</p></div></div></section>
    <section className="mf-section mf-section--soft"><div className="mf-container"><SectionIntro eyebrow="HOW WE WORK" title="Grounded in three operating principles." /><div className="mf-grid-3">{principles.map((principle, index) => <article className="mf-card mf-pillar" key={principle.title}><Tag tone="info">0{index + 1} / PRINCIPLE</Tag><h3>{principle.title}</h3><p>{principle.copy}</p></article>)}</div></div></section>
    <section className="mf-section"><div className="mf-container"><SectionIntro eyebrow="SELECTED COLLABORATIONS" title="Different organizations. Different constraints. Durable foundations." copy="Our public project stories include work with NC Waterfalls, Barclay Rex, Garden State Equality, and the Community Coalition on Race. We share the context and evidence that can be substantiated." /><div className="mf-grid-4"><article className="mf-card mf-pillar"><h3>Knowledge archives</h3><p>Structured content and discovery for research-rich public resources.</p></article><article className="mf-card mf-pillar"><h3>Commerce platforms</h3><p>Practical systems that connect customer experience with business operations.</p></article><article className="mf-card mf-pillar"><h3>Mission-driven outreach</h3><p>Digital channels that help nonprofits communicate and organize.</p></article><article className="mf-card mf-pillar"><h3>Ongoing stewardship</h3><p>Hosting, maintenance, and technical guidance beyond initial release.</p></article></div><div style={{marginTop:28}}><Button href="/work" variant="secondary">See documented project stories ↗</Button></div></div></section>
    <section className="mf-section"><div className="mf-container mf-band"><p className="mf-eyebrow">LET’S WORK THROUGH IT</p><h2>Talk to the people who will help shape and support the system.</h2><p>Bring the goal, the constraint, or the existing platform. We will help define the conversation from there.</p><Button href="/contact">Start a project conversation ↗</Button></div></section>
  </div></Layout>;
}
